### ISSUE TITLE
license

### ISSUE THREAD

**Issue by PaluMacil** [benpye/sharpui#1]
Hello,

I just came across your project, noting that it seems to support .Net Core but needs updates, porting from project.json to csproj and large amounts of docs. Would you be willing to add a license so that others can use this? Since it'll need a fair bit of updates, will you be likely to work on it? If not, I'd humbly ask that you consider a lenient license such as MIT, WTFPL, public domain dedication, or BSD since I tend to prefer MIT and would like to fork and continue this work.

**Comment by benpye** [comment]
Hey,
I haven't had a chance to work on this recently. I'm happy to dedicate it
to the public domain however. I'll also happily review any pull requests.

**Comment by PaluMacil** [comment]
Thanks for the quick reply. I'll keep an eye out for a public domain dedication or license and start some work once that's committed.

**Comment by benpye** [comment]
Committed in 42723f549cf00a96cc2d1d9fec233495eb35bd7b

**Comment by PaluMacil** [comment]
Thanks again :)
